"""IP blockability validation (see DESIGN.md §8.3).

``is_ip_blockable`` is the single gate for all rule creation.  Call it before
inserting any rule into the database.  Returns ``(True, None)`` if the IP is
eligible to be blocked, or ``(False, reason)`` where *reason* is a short
machine-readable string the API returns to callers.
"""

from __future__ import annotations

import ipaddress
import json
import socket
import struct
from pathlib import Path

import structlog

log = structlog.get_logger(__name__)

_PRIVATE_RANGES: list[ipaddress.IPv4Network] = [
    ipaddress.IPv4Network("10.0.0.0/8"),
    ipaddress.IPv4Network("172.16.0.0/12"),
    ipaddress.IPv4Network("192.168.0.0/16"),
]
_LOOPBACK: ipaddress.IPv4Network = ipaddress.IPv4Network("127.0.0.0/8")
_LINK_LOCAL: ipaddress.IPv4Network = ipaddress.IPv4Network("169.254.0.0/16")

_XBL_ALLOWLIST_PATH: Path = (
    Path(__file__).resolve().parent.parent.parent / "data" / "xbox-live-allowlist.json"
)


def load_xbl_allowlist() -> list[tuple[str, int]]:
    """Load Xbox Live allowlist entries from ``data/xbox-live-allowlist.json``.

    Returns an empty list if the file does not exist.  Logs at WARNING because
    this is a security-relevant check being skipped — visible in journalctl by
    default.  The file is generated by Phase 3; this function is safe to call
    before that (Stage 2 dev environments) and will just return [].
    """
    if not _XBL_ALLOWLIST_PATH.exists():
        log.warning(
            "xbox-live-allowlist.json not found — xbl_allowlist check will be skipped "
            "(expected until Phase 3 generates the file)",
            path=str(_XBL_ALLOWLIST_PATH),
        )
        return []
    try:
        data = json.loads(_XBL_ALLOWLIST_PATH.read_text(encoding="utf-8"))
        entries: list[tuple[str, int]] = []
        for entry in data.get("entries", []):
            ip = entry.get("ip")
            cidr = entry.get("cidr", 32)
            if ip:
                entries.append((str(ip), int(cidr)))
        return entries
    except Exception as exc:  # noqa: BLE001
        log.warning("failed to load xbox-live-allowlist.json", error=str(exc))
        return []


def get_default_gateway() -> str | None:
    """Return the default gateway IP parsed from ``/proc/net/route``.

    Returns ``None`` if ``/proc/net/route`` is unavailable (non-Linux) or if
    no default route is configured.  Does not require elevated privileges.
    """
    try:
        with open("/proc/net/route", encoding="ascii") as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) < 3:
                    continue
                # Default route: Destination == "00000000"
                if parts[1] != "00000000":
                    continue
                gw_hex = parts[2]
                if gw_hex == "00000000":
                    continue  # route with no gateway (e.g. directly connected)
                # Value is stored in host byte order (little-endian on x86/ARM)
                gw_int = int(gw_hex, 16)
                return socket.inet_ntoa(struct.pack("<I", gw_int))
    except (OSError, ValueError):
        pass
    return None


def get_bridge_ip(iface: str = "br0") -> str | None:
    """Return the IPv4 address of *iface* via ``SIOCGIFADDR``.

    Returns ``None`` on non-Linux (``fcntl`` not available) or if the interface
    does not exist.  Does not require elevated privileges.
    """
    try:
        import fcntl  # type: ignore[import-not-found]  # Linux-only stdlib

        siocgifaddr = 0x8915
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            result = fcntl.ioctl(
                s.fileno(),
                siocgifaddr,
                struct.pack("256s", iface[:15].encode("ascii")),
            )
        return socket.inet_ntoa(result[20:24])
    except (ImportError, OSError, struct.error):
        return None


def is_ip_blockable(
    ip_address: str,
    cidr_prefix: int = 32,
    *,
    xbl_allowlist: list[tuple[str, int]] | None = None,
    gateway_ip: str | None = None,
    bridge_ip: str | None = None,
) -> tuple[bool, str | None]:
    """Check whether *ip_address*/*cidr_prefix* is eligible for the blocklist.

    Returns ``(True, None)`` if blockable.  Returns ``(False, reason)`` where
    *reason* is one of:

    * ``'invalid'``    — not a parseable IPv4 address/prefix
    * ``'loopback'``   — overlaps 127.0.0.0/8
    * ``'private'``    — overlaps an RFC 1918 range
    * ``'link-local'`` — overlaps 169.254.0.0/16
    * ``'xbox-live'``  — overlaps the Xbox Live allowlist
    * ``'gateway'``    — matches the detected (or provided) default gateway IP
    * ``'bridge'``     — matches the detected (or provided) br0 IP

    Keyword-only parameters for injection (tests and callers that already have
    network info):

    * *xbl_allowlist*: inject list of ``(ip, cidr)`` tuples.  When ``None``,
      loaded from ``data/xbox-live-allowlist.json``.
    * *gateway_ip*: explicit gateway IP string.  When ``None``, auto-detected
      via ``/proc/net/route``; if detection also returns ``None`` the check is
      skipped (expected on Windows / dev environments with no default route).
    * *bridge_ip*: explicit bridge IP string.  When ``None``, auto-detected
      via ``SIOCGIFADDR`` on ``br0``; if detection returns ``None`` the check
      is skipped.
    """
    try:
        net = ipaddress.IPv4Network(f"{ip_address}/{cidr_prefix}", strict=False)
    except ValueError:
        return False, "invalid"

    if net.overlaps(_LOOPBACK):
        return False, "loopback"

    for private in _PRIVATE_RANGES:
        if net.overlaps(private):
            return False, "private"

    if net.overlaps(_LINK_LOCAL):
        return False, "link-local"

    effective_allowlist = xbl_allowlist if xbl_allowlist is not None else load_xbl_allowlist()
    for xbl_ip, xbl_cidr in effective_allowlist:
        try:
            xbl_net = ipaddress.IPv4Network(f"{xbl_ip}/{xbl_cidr}", strict=False)
            if net.overlaps(xbl_net):
                return False, "xbox-live"
        except ValueError:
            continue

    effective_gateway = gateway_ip if gateway_ip is not None else get_default_gateway()
    if effective_gateway is not None:
        try:
            if ipaddress.IPv4Address(effective_gateway) in net:
                return False, "gateway"
        except ValueError:
            pass

    effective_bridge = bridge_ip if bridge_ip is not None else get_bridge_ip()
    if effective_bridge is not None:
        try:
            if ipaddress.IPv4Address(effective_bridge) in net:
                return False, "bridge"
        except ValueError:
            pass

    return True, None
